from agents.base_agent import NemotronAgent
from tools.github_client import GitHubClient
from typing import Dict
import time

PR_CREATOR_PROMPT = """You are a PR Creator Agent. Your job is to:
1. Create well-documented GitHub pull requests
2. Write clear PR descriptions with CVE details
3. Include testing results and validation info
4. Follow best practices for security patches

Make PRs that developers will want to merge immediately."""

class PRCreatorAgent(NemotronAgent):
    def __init__(self):
        super().__init__("PRCreator", PR_CREATOR_PROMPT)
        self.github = GitHubClient()
    
    def _build_template_pr_body(self, cve_id: str, cvss_score: float, package: str, 
                                current_version: str, secure_version: str, summary: str,
                                nvd_context: str = '') -> str:
        """Build a template PR body (fallback when NVD context is not available)"""
        pr_body = f"""## 🔒 Security Patch: {cve_id}

**CVSS Score**: {cvss_score}/10 ({'CRITICAL' if cvss_score >= 9 else 'HIGH' if cvss_score >= 7 else 'MEDIUM'})

### 🐛 Vulnerability Details

{summary if summary else f'Security vulnerability in {package}'}

### ✅ Fix Applied

**Package**: `{package}`  
**Previous Version**: `{current_version}`  
**New Version**: `{secure_version}`  
**Status**: Upgraded to secure version

### 📚 References

- [OSV: {cve_id}](https://osv.dev/vulnerability/{cve_id})
- [NVD: {cve_id}](https://nvd.nist.gov/vuln/detail/{cve_id})

---

*🤖 Generated by PatchForge - Autonomous CVE Patching Agent*
"""
        return pr_body
    
    def create_pr(self, patch_data: Dict, validation_data: Dict, 
                  repo_name: str, research_data: Dict, cve_explanation: str = None,
                  attempts: int = 1) -> str:
        """Create a GitHub PR with the patch
        
        Args:
            patch_data: Patch information
            validation_data: Validation results
            repo_name: GitHub repository name
            research_data: CVE research data
            cve_explanation: Optional CVE explanation from Nemotron
            attempts: Number of attempts made (for ReAct loop info)
        """
        self.logger.info(f"📝 Creating PR for {patch_data['cve_id']}")
        
        cve_id = patch_data['cve_id']
        branch_name = f"security-patch-{cve_id.lower()}-{int(time.time())}"
        
        # Create branch
        self.github.create_branch(repo_name, branch_name)
        
        # Commit patch
        self.github.commit_file(
            repo_name=repo_name,
            file_path=patch_data['file_path'],
            content=patch_data['patched_content'],
            message=f"fix: {patch_data['description']}",
            branch=branch_name
        )
        
        # Generate PR body using Nemotron with NVD context (NEW: Professional PR generation)
        cvss_score = research_data.get('cvss_score', 0)
        package = research_data.get('package', patch_data.get('package', 'unknown'))
        current_version = research_data.get('current_version', patch_data.get('old_version', 'unknown'))
        secure_version = research_data.get('secure_version', patch_data.get('new_version', 'unknown'))
        summary = research_data.get('summary', '')
        nvd_context = research_data.get('nvd_context', '')
        
        # Use Nemotron to generate professional PR description with NVD context
        if nvd_context and "Error" not in nvd_context and "No detailed information" not in nvd_context:
            self.logger.info("📝 Generating professional PR description with NVD context")
            
            pr_prompt = f"""You are a senior DevSecOps engineer writing a pull request description for a security fix.

CVE: {cve_id}
Package: {package}
Version: {current_version} → {secure_version}
CVSS Score: {cvss_score}/10

Full NVD (National Vulnerability Database) Context:
---
{nvd_context}
---

Write a professional, CISO-ready PR description in markdown format. Include:

1. **Clear Title Section**: Security Patch with CVE ID
2. **Vulnerability Summary**: What the CVE allows attackers to do (use NVD details)
3. **Exploit Risk**: Severity and potential impact
4. **Fix Details**: What version fixes it and why
5. **Testing**: Validation results
6. **References**: Links to NVD and official sources

Make it authoritative, grounded in the NVD data, and ready for security review.
Use professional security terminology. Reference the NVD data to make it credible.

Return ONLY the markdown PR body, nothing else. Do not include code blocks or explanations."""
            
            try:
                generated_pr_body = self.call_nemotron(pr_prompt, temperature=0.3)
                if generated_pr_body and len(generated_pr_body) > 100:
                    # Use the generated PR body as the base
                    pr_body = generated_pr_body.strip()
                    # Remove markdown code blocks if present
                    if pr_body.startswith('```'):
                        lines = pr_body.split('\n')
                        if lines[0].startswith('```'):
                            lines = lines[1:]
                        if lines[-1].strip() == '```':
                            lines = lines[:-1]
                        pr_body = '\n'.join(lines)
                    self.logger.info("✅ Generated professional PR description with NVD context")
                else:
                    # Fallback to template if generation failed
                    self.logger.warning("⚠️  PR generation returned empty result, using template")
                    pr_body = self._build_template_pr_body(cve_id, cvss_score, package, current_version, secure_version, summary, nvd_context)
            except Exception as e:
                self.logger.error(f"❌ Error generating PR description: {e}")
                # Fallback to template
                pr_body = self._build_template_pr_body(cve_id, cvss_score, package, current_version, secure_version, summary, nvd_context)
        else:
            # Use template if no NVD context
            pr_body = self._build_template_pr_body(cve_id, cvss_score, package, current_version, secure_version, summary, nvd_context)
        
        # Add CVE explanation if provided (from --explain flag)
        if cve_explanation:
            pr_body += f"""

### 📚 Detailed CVE Analysis

{cve_explanation}

"""
        
        # Add ReAct loop information if multiple attempts were made
        if attempts > 1:
            pr_body += f"""### 🔄 ReAct Loop Refinement

This patch was refined through **{attempts} attempts** using PatchForge's ReAct-style retry loop:

1. **Attempt 1**: Initial patch generated (single package update)
2. **Validation**: Failed with dependency conflicts
3. **Refinement**: Nemotron analyzed errors and coordinated multi-package updates
4. **Attempt {attempts}**: Refined patch with coordinated updates passed all validation checks

The final patch resolves all dependency conflicts through coordinated package upgrades.

"""
            
            # Add information about multi-package updates if available
            refinement_changes = patch_data.get('refinement_changes', [])
            if refinement_changes:
                pr_body += f"""### 📦 Multi-Package Updates

To resolve dependency conflicts, the following packages were automatically updated:

"""
                # Filter and format changes
                package_updates = []
                for change in refinement_changes:
                    change_str = change.strip()
                    if change_str and ('==' in change_str or '>=' in change_str or '~=' in change_str):
                        package_updates.append(change_str)
                
                # Show unique package updates
                seen = set()
                for update in package_updates[:10]:  # Limit to 10 updates
                    # Extract package name for deduplication
                    pkg_name = update.split()[0] if update.split() else update
                    if pkg_name not in seen:
                        pr_body += f"- `{update}`\n"
                        seen.add(pkg_name)
                
                if package_updates:
                    pr_body += "\n"
                    pr_body += "*These packages were automatically upgraded to resolve dependency conflicts.*\n\n"
        
        # Add fix details and validation if not already in generated PR body
        if "### ✅ Fix Applied" not in pr_body and "## Fix Applied" not in pr_body and "Fix Applied" not in pr_body:
            pr_body += f"""

### ✅ Fix Applied

Updated `{patch_data['file_path']}` to address the vulnerability.

**Package**: `{package}`  
**Previous Version**: `{current_version}`  
**New Version**: `{secure_version}`  
**Status**: Upgraded to secure version

### 🧪 Validation Results

{'✅ All checks passed' if validation_data['passed'] else '⚠️ Validation had issues'}

```
{validation_data['message']}
```

### 📚 References

- [OSV: {cve_id}](https://osv.dev/vulnerability/{cve_id})
- [NVD: {cve_id}](https://nvd.nist.gov/vuln/detail/{cve_id})

---

*🤖 Generated by PatchForge - Autonomous CVE Patching Agent*  
*Powered by NVIDIA Nemotron with RAG over NVD*  
*ReAct Loop: {'Enabled' if attempts > 1 else 'Not needed'}*
"""
        
        # Create PR
        pr_url = self.github.create_pr(
            repo_name=repo_name,
            title=f"🔒 Security: Fix {cve_id} in {package}",
            body=pr_body,
            head_branch=branch_name,
            base_branch="main"
        )
        
        self.logger.info(f"✅ PR created: {pr_url}")
        return pr_url
